# Generated by Django 5.1.6 on 2026-03-31 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComparisonRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run_type",
                    models.CharField(
                        choices=[
                            ("version_diff", "Version Diff"),
                            ("internal_vs_external", "Internal vs External"),
                            ("policy_vs_control", "Policy vs Control"),
                            ("cross_document", "Cross Document"),
                        ],
                        max_length=32,
                    ),
                ),
                ("target_document_ids", models.JSONField(default=list)),
                ("config_snapshot", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("degraded", "Degraded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("correlation_id", models.CharField(max_length=64)),
                (
                    "source_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparison_sources",
                        to="documents.policydocument",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
