# Generated by Django 5.1.6 on 2026-03-31 09:26

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="SELECT 1;",
        ),
        migrations.CreateModel(
            name="ControlStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "statement_type",
                    models.CharField(
                        choices=[
                            ("obligation", "Obligation"),
                            ("control", "Control"),
                            ("procedure_step", "Procedure Step"),
                            ("timeline", "Timeline"),
                            ("threshold", "Threshold"),
                            ("exception_rule", "Exception Rule"),
                            ("approval_rule", "Approval Rule"),
                        ],
                        max_length=32,
                    ),
                ),
                ("raw_text", models.TextField()),
                ("normalized_text", models.TextField()),
                (
                    "subject_entity",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "action_verb",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("condition_text", models.TextField(blank=True, null=True)),
                (
                    "deadline_text",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "threshold_text",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("owner_role", models.CharField(blank=True, max_length=255, null=True)),
                ("schema_valid", models.BooleanField(default=True)),
                ("extraction_confidence", models.FloatField(default=0.0)),
                ("extraction_version", models.CharField(default="v1", max_length=50)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        dimensions=8,
                        null=True,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statements",
                        to="documents.policydocument",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statements",
                        to="documents.documentsection",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["document", "statement_type"],
                        name="statements__documen_aba93c_idx",
                    )
                ],
            },
        ),
    ]
