# Generated by Django 5.1.6 on 2026-03-31 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("comparisons", "0001_initial"),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("version_label", models.CharField(max_length=50)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("sectioning", "Sectioning"),
                            ("statement_extraction", "Statement Extraction"),
                            ("contradiction_analysis", "Contradiction Analysis"),
                            ("memo_generation", "Memo Generation"),
                        ],
                        max_length=32,
                    ),
                ),
                ("template_text", models.TextField()),
                ("schema_version", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GuidanceSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("fca_guidance", "FCA Guidance"),
                            ("industry_standard", "Industry Standard"),
                            ("internal_standard", "Internal Standard"),
                            ("board_standard", "Board Standard"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("effective_date", models.DateField()),
                ("active", models.BooleanField(default=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guidance_source",
                        to="documents.policydocument",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ModelExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("task_name", models.CharField(max_length=255)),
                ("provider_name", models.CharField(max_length=255)),
                ("model_name", models.CharField(max_length=255)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("input_token_estimate", models.PositiveIntegerField(default=0)),
                ("output_token_estimate", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("timeout", "Timeout"),
                            ("schema_fail", "Schema Fail"),
                            ("provider_error", "Provider Error"),
                            ("fallback_used", "Fallback Used"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "cost_estimate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "comparison_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="model_logs",
                        to="comparisons.comparisonrun",
                    ),
                ),
                (
                    "prompt_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executions",
                        to="observability.promptversion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
