# Generated by Django 5.1.6 on 2026-03-31 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("comparisons", "0001_initial"),
        ("documents", "0001_initial"),
        ("observability", "0001_initial"),
        ("statements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConflictFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conflict_type",
                    models.CharField(
                        choices=[
                            ("direct_contradiction", "Direct Contradiction"),
                            ("weaker_internal_control", "Weaker Internal Control"),
                            ("missing_control", "Missing Control"),
                            ("stale_reference", "Stale Reference"),
                            ("threshold_conflict", "Threshold Conflict"),
                            ("timeline_conflict", "Timeline Conflict"),
                            ("approval_conflict", "Approval Conflict"),
                            ("terminology_drift", "Terminology Drift"),
                            ("coverage_gap", "Coverage Gap"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("needs_review", "Needs Review"),
                            ("dismissed", "Dismissed"),
                            ("confirmed", "Confirmed"),
                            ("escalated", "Escalated"),
                            ("resolved", "Resolved"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("requires_review", models.BooleanField(default=True)),
                ("reason_summary", models.TextField()),
                ("rules_triggered", models.JSONField(default=list)),
                (
                    "model_version",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "comparison_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts",
                        to="comparisons.comparisonrun",
                    ),
                ),
                (
                    "source_statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_conflicts",
                        to="statements.controlstatement",
                    ),
                ),
                (
                    "target_statement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="target_conflicts",
                        to="statements.controlstatement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvidenceCitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "citation_role",
                    models.CharField(
                        choices=[
                            ("source", "Source"),
                            ("target", "Target"),
                            ("context", "Context"),
                        ],
                        max_length=16,
                    ),
                ),
                ("excerpt_text", models.TextField()),
                (
                    "conflict_flag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations",
                        to="findings.conflictflag",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.policydocument",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.documentsection",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FindingMemo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommended_action",
                    models.CharField(
                        choices=[
                            ("review", "Review"),
                            ("confirm", "Confirm"),
                            ("dismiss", "Dismiss"),
                            ("escalate", "Escalate"),
                            ("request_policy_update", "Request Policy Update"),
                        ],
                        max_length=32,
                    ),
                ),
                ("summary", models.TextField()),
                ("structured_rationale", models.JSONField(default=dict)),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "conflict_flag",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memo",
                        to="findings.conflictflag",
                    ),
                ),
                (
                    "prompt_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memos",
                        to="observability.promptversion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="conflictflag",
            index=models.Index(
                fields=["status", "severity", "conflict_type", "created_at"],
                name="findings_co_status_1c77b0_idx",
            ),
        ),
    ]
