# Generated by Django 5.1.6 on 2026-03-31 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PolicyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("internal_policy", "Internal Policy"),
                            ("procedure", "Procedure"),
                            ("control_library", "Control Library"),
                            ("guidance", "Guidance"),
                            ("standard", "Standard"),
                            ("board_paper", "Board Paper"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("source_name", models.CharField(max_length=255)),
                (
                    "jurisdiction",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "domain_area",
                    models.CharField(
                        choices=[
                            ("complaints", "Complaints"),
                            ("consumer_support", "Consumer Support"),
                            ("communications", "Communications"),
                            ("escalations", "Escalations"),
                            ("governance", "Governance"),
                            ("vulnerable_customers", "Vulnerable Customers"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("owner_team", models.CharField(blank=True, max_length=255, null=True)),
                ("version_label", models.CharField(max_length=50)),
                ("effective_date", models.DateField()),
                ("is_external_source", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("retired", "Retired"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("storage_path", models.CharField(max_length=500)),
                ("sha256_checksum", models.CharField(db_index=True, max_length=64)),
                ("content_text", models.TextField(default="")),
                (
                    "supersedes_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="superseded_by",
                        to="documents.policydocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("section_index", models.PositiveIntegerField()),
                ("heading", models.CharField(blank=True, max_length=255, null=True)),
                ("text", models.TextField()),
                ("char_start", models.PositiveIntegerField(default=0)),
                ("char_end", models.PositiveIntegerField(default=0)),
                ("page_number", models.PositiveIntegerField(blank=True, null=True)),
                ("parser_confidence", models.FloatField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="documents.policydocument",
                    ),
                ),
            ],
            options={
                "ordering": ["section_index"],
            },
        ),
        migrations.AddIndex(
            model_name="policydocument",
            index=models.Index(
                fields=["document_type", "domain_area", "status", "effective_date"],
                name="documents_p_documen_082cf9_idx",
            ),
        ),
    ]
