# Generated by Django 5.1.6 on 2026-03-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entity_type", models.CharField(max_length=100)),
                ("entity_id", models.CharField(max_length=64)),
                ("event_type", models.CharField(max_length=100)),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("user", "User"),
                            ("reviewer", "Reviewer"),
                            ("job", "Job"),
                        ],
                        max_length=16,
                    ),
                ),
                ("actor_id", models.CharField(blank=True, max_length=64, null=True)),
                ("correlation_id", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id", "created_at"],
                        name="audits_audi_entity__a8ed35_idx",
                    )
                ],
            },
        ),
    ]
