# Generated by Django 5.1.6 on 2026-03-31 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("findings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("queue_name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unassigned", "Unassigned"),
                            ("assigned", "Assigned"),
                            ("in_review", "In Review"),
                            ("approved", "Approved"),
                            ("overridden", "Overridden"),
                            ("dismissed", "Dismissed"),
                            ("escalated", "Escalated"),
                            ("closed", "Closed"),
                        ],
                        default="unassigned",
                        max_length=16,
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            ("low_confidence", "Low Confidence"),
                            ("high_severity", "High Severity"),
                            ("schema_failure", "Schema Failure"),
                            ("stale_reference", "Stale Reference"),
                            ("missing_control", "Missing Control"),
                            ("manual_sampling", "Manual Sampling"),
                            ("provider_failure", "Provider Failure"),
                        ],
                        max_length=32,
                    ),
                ),
                ("sla_due_at", models.DateTimeField()),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conflict_flag",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_task",
                        to="findings.conflictflag",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewerAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("override", "Override"),
                            ("dismiss", "Dismiss"),
                            ("escalate", "Escalate"),
                            ("request_update", "Request Update"),
                            ("mark_false_positive", "Mark False Positive"),
                            ("close", "Close"),
                        ],
                        max_length=32,
                    ),
                ),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("comment", models.TextField()),
                (
                    "override_reason_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="reviews.reviewtask",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="reviewtask",
            index=models.Index(
                fields=["status", "queue_name", "sla_due_at"],
                name="reviews_rev_status_85429d_idx",
            ),
        ),
    ]
