# Generated by Django 5.1.6 on 2026-03-31 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentLineage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("supersedes", "Supersedes"),
                            ("derived_from", "Derived From"),
                            ("references", "References"),
                            ("implements", "Implements"),
                            ("aligned_to", "Aligned To"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "child_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_lineage_links",
                        to="documents.policydocument",
                    ),
                ),
                (
                    "parent_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_lineage_links",
                        to="documents.policydocument",
                    ),
                ),
            ],
            options={
                "unique_together": {("parent_document", "child_document", "relationship_type")},
            },
        ),
    ]
